name: Send Hacker News Email

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发工作流
  workflow_dispatch:       # 手动触发

jobs:
  run-python-script:
    name: Run Python Script
    runs-on: ubuntu-latest
    environment: GMAIL_ADDRESS  # 使用你配置的环境 GMAIL_ADDRESS

    steps:
      # 第一步：检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      # 第三步：安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 第四步：运行脚本
      - name: Run script
        env:
          PROXY: ${{ secrets.PROXY }}  # 引用 GitHub 密钥 PROXIES
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}  # 引用 GitHub 密钥 EMAIL_ADDRESS
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # 引用 GitHub 密钥 EMAIL_PASSWORD
          TO_EMAILS: ${{ secrets.TO_EMAILS }}  # 引用 GitHub 密钥 TO_EMAILS
        run: |
          python -m src.main